### ISSUE TITLE
A small bug in save_checkpoint.

### ISSUE THREAD

**Issue by liuhao-lh** [sandwichfish/VirFace#3]
Thanks for your excellent work!

https://github.com/sandwichfish/VirFace/blob/464ad88e01be58c741ab4129aaab78b521150530/train.py#L311-L312 .update will return NoneType, so no checkpoint is saved.

The following code works.
`save_dict = {'epoch': epoch + 1, 'optimizer': optimizer.state_dict()}`
`save_dict.update({k: model[k].state_dict() for k in model.keys()})`

**Comment by sandwichfish** [comment]
code have updated. Thank you for your feedback.
