### ISSUE TITLE
如何使用MS1M_Arcface数据集

### ISSUE THREAD

**Issue by xxx46408** [sandwichfish/VirFace#4]
如何将insightface中的MS1M_Arcface的数据集用到您的项目中进行训练呢

**Comment by sandwichfish** [comment]
将其中的图像单独提取出来，使用给定的meta文件进行训练就好

**Comment by xxx46408** [comment]
请问用于验证的cfp数据集的pair应该去哪儿找呢

**Comment by sandwichfish** [comment]
可以按insightface里面的方式进行测试

**Comment by xxx46408** [comment]
如果想按照论文中The Pipeline of VirFace进行loop ,应该怎么做呢

**Comment by sandwichfish** [comment]
可以套用GAN的训练方式，将loss_MSE 和 KL_loss 放到VAE的训练过程中。分别设置model['backbone].eval()和model['generator'].eval()使用不同的optimizer进行分开训练。目前代码的方式和论文中的方式的结果是差不多的。
